INSERT INTO workspaces (
  id,
  name,
  slug,
  focus,
  default_currency,
  created_at,
  updated_at
) VALUES (
  'ws-1',
  'Northbound Studio',
  'northbound-studio',
  'Travel-led creator business',
  'CAD',
  '2026-04-10T09:00:00Z',
  '2026-04-18T12:00:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO invoices (
  id,
  workspace_id,
  project_id,
  person_id,
  invoice_number,
  direction,
  status,
  issue_date,
  due_date,
  total_amount,
  note,
  created_at,
  updated_at
) VALUES
(
  'invoice-1',
  'ws-1',
  'project-1',
  NULL,
  'NR-2026-014',
  'Outbound',
  'Sent',
  '2026-04-18',
  '2026-05-02',
  4200,
  'First sponsor milestone invoice for Northern Routes.',
  '2026-04-18T08:35:00Z',
  '2026-04-18T08:35:00Z'
),
(
  'invoice-2',
  'ws-1',
  'project-1',
  'person-2',
  'AP-2026-003',
  'Inbound',
  'Paid',
  '2026-04-17',
  '2026-04-21',
  780,
  'Contractor invoice for second camera field support.',
  '2026-04-17T16:45:00Z',
  '2026-04-18T11:20:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO payments (
  id,
  workspace_id,
  invoice_id,
  amount,
  paid_at,
  method,
  proof_document_id,
  note,
  created_at,
  updated_at
) VALUES
(
  'payment-1',
  'ws-1',
  'invoice-2',
  780,
  '2026-04-18',
  'Bank transfer',
  'document-5',
  'Paid in full after field support wrap.',
  '2026-04-18T11:22:00Z',
  '2026-04-18T11:22:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (
  id,
  workspace_id,
  linked_type,
  linked_id,
  file_name,
  document_type,
  mime_type,
  storage_path,
  status,
  note,
  created_at,
  updated_at
) VALUES
(
  'document-1',
  'ws-1',
  'Trip',
  'trip-1',
  'banff-trip-brief.svg',
  'Brief',
  'image/svg+xml',
  'workspace/ws-1/trips/trip-1/banff-trip-brief.svg',
  'Linked',
  'Opening brief covering sponsor visuals, route plan, and field capture goals.',
  '2026-04-11T16:00:00Z',
  '2026-04-11T16:00:00Z'
),
(
  'document-2',
  'ws-1',
  'Expense',
  'expense-2',
  'hotel-receipt-banff.svg',
  'Receipt',
  'image/svg+xml',
  'workspace/ws-1/expenses/expense-2/hotel-receipt-banff.svg',
  'Needs review',
  'Receipt placeholder created so the team can track the missing upload against the expense record.',
  '2026-04-18T09:02:00Z',
  '2026-04-18T09:02:00Z'
),
(
  'document-3',
  'ws-1',
  'Person',
  'person-2',
  'alex-park-contractor-agreement.svg',
  'Agreement',
  'image/svg+xml',
  'workspace/ws-1/people/person-2/alex-park-contractor-agreement.svg',
  'Pending signature',
  'Contractor agreement draft created but still waiting for signed return copy.',
  '2026-04-18T09:12:00Z',
  '2026-04-18T09:12:00Z'
),
(
  'document-4',
  'ws-1',
  'Invoice',
  'invoice-1',
  'nr-2026-014-invoice.svg',
  'Invoice',
  'image/svg+xml',
  'workspace/ws-1/invoices/invoice-1/nr-2026-014-invoice.svg',
  'Linked',
  'Client-facing invoice for the first Northern Routes sponsor milestone.',
  '2026-04-18T08:40:00Z',
  '2026-04-18T08:40:00Z'
),
(
  'document-5',
  'ws-1',
  'Payment',
  'payment-1',
  'alex-park-payment-proof.svg',
  'Payment Proof',
  'image/svg+xml',
  'workspace/ws-1/payments/payment-1/alex-park-payment-proof.svg',
  'Linked',
  'Bank transfer confirmation for contractor payment.',
  '2026-04-18T11:25:00Z',
  '2026-04-18T11:25:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO projects (
  id,
  workspace_id,
  title,
  project_type,
  status,
  planned_start,
  planned_end,
  budget_estimate,
  commercial_objective,
  revenue_outcome,
  timeline,
  linked_trip_ids,
  linked_production_ids,
  linked_expense_ids,
  linked_person_ids,
  closure_status,
  narrative,
  created_at,
  updated_at
) VALUES
(
  'project-1',
  'ws-1',
  'Northern Routes Series',
  'Series',
  'Active',
  '2026-04-10',
  '2026-05-25',
  9600,
  'Build a sponsor-ready travel series and convert audience interest into affiliate and brand revenue.',
  'Target one tourism partner and one camera accessory sponsor.',
  'April to late May rollout.',
  ARRAY['trip-1'],
  ARRAY['production-1'],
  ARRAY['expense-1','expense-2'],
  ARRAY['person-1','person-2'],
  'Soft Close',
  'The project is active, but closure should remain blocked until the international trip dossier and production role confirmations are complete.',
  '2026-04-10T09:00:00Z',
  '2026-04-18T12:00:00Z'
),
(
  'project-2',
  'ws-1',
  'Studio Workflow Refresh',
  'Internal Ops',
  'Planning',
  '2026-04-20',
  '2026-05-02',
  1800,
  'Improve editing throughput and standardize post-production systems for future client delivery.',
  'Reduce turnaround time by 20 percent.',
  'Two-week implementation sprint.',
  ARRAY[]::TEXT[],
  ARRAY['production-2'],
  ARRAY[]::TEXT[],
  ARRAY['person-3'],
  'Open',
  'This internal project has a clear commercial intent but still needs linked expense and milestone evidence.',
  '2026-04-16T09:00:00Z',
  '2026-04-18T12:00:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO trips (
  id,
  workspace_id,
  project_id,
  title,
  trip_type,
  purpose,
  origin_summary,
  destination_summary,
  start_date,
  end_date,
  pre_trip_complete,
  during_trip_complete,
  post_trip_complete,
  brief_saved,
  spouse_or_contractor,
  estimated_budget,
  actual_spend,
  closure_status,
  outcome_notes,
  created_at,
  updated_at
) VALUES
(
  'trip-1',
  'ws-1',
  'project-1',
  'Banff Opening Shoot',
  'International',
  'Capture destination footage for the Northern Routes series and develop sponsor-facing visuals.',
  'Toronto',
  'Banff and Canmore',
  '2026-04-12',
  '2026-04-18',
  TRUE,
  TRUE,
  FALSE,
  TRUE,
  TRUE,
  4300,
  3890,
  'Soft Close',
  'Daily logs are present, but the post-trip narrative and contractor proof are still incomplete.',
  '2026-04-11T15:00:00Z',
  '2026-04-18T12:00:00Z'
),
(
  'trip-2',
  'ws-1',
  'project-1',
  'Montreal Brand Scout',
  'Work',
  'Meet two hospitality prospects and capture scouting footage for a pitch deck.',
  'Toronto',
  'Montreal',
  '2026-04-25',
  '2026-04-26',
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  FALSE,
  980,
  0,
  'Open',
  'Planned trip with no opening questionnaire completed yet.',
  '2026-04-18T10:00:00Z',
  '2026-04-18T10:00:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO productions (
  id,
  workspace_id,
  project_id,
  title,
  content_type,
  platform_intent,
  shoot_date,
  location,
  business_purpose,
  published_url,
  publish_target_date,
  role_documentation_complete,
  linked_expense_ids,
  linked_person_ids,
  closure_status,
  outcome_notes,
  created_at,
  updated_at
) VALUES
(
  'production-1',
  'ws-1',
  'project-1',
  'Episode 1 Hero Cut',
  'Long-form video',
  'YouTube + short-form cutdowns',
  '2026-04-14',
  'Banff Gondola and downtown Banff',
  'Launch the series with a sponsor-quality anchor piece that supports audience growth and monetization.',
  NULL,
  '2026-04-24',
  FALSE,
  ARRAY['expense-1'],
  ARRAY['person-1','person-2'],
  'Soft Close',
  'Primary footage is captured, but role documentation and publish status still need confirmation.',
  '2026-04-14T08:00:00Z',
  '2026-04-18T12:00:00Z'
),
(
  'production-2',
  'ws-1',
  'project-2',
  'Editing Bay Setup Walkthrough',
  'Process reel',
  'Instagram Reels',
  '2026-04-21',
  'Studio',
  'Document the upgraded studio workflow and produce a behind-the-scenes brand asset.',
  'https://example.com/studio-refresh',
  '2026-04-22',
  TRUE,
  ARRAY[]::TEXT[],
  ARRAY['person-3'],
  'Final Close',
  'Published and operationally complete.',
  '2026-04-17T11:00:00Z',
  '2026-04-18T12:00:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO expenses (
  id,
  workspace_id,
  project_id,
  trip_id,
  production_id,
  title,
  category,
  amount,
  expense_date,
  business_purpose,
  content_connection,
  receipt_attached,
  asset_linked,
  created_at,
  updated_at
) VALUES
(
  'expense-1',
  'ws-1',
  'project-1',
  'trip-1',
  'production-1',
  'Drone rental',
  'Production',
  420,
  '2026-04-13',
  'Capture hero aerial footage for the Northern Routes opening episode.',
  'Episode 1 Hero Cut',
  TRUE,
  FALSE,
  '2026-04-13T09:30:00Z',
  '2026-04-13T09:30:00Z'
),
(
  'expense-2',
  'ws-1',
  'project-1',
  'trip-1',
  NULL,
  'Hotel stay',
  'Travel',
  1180,
  '2026-04-14',
  '',
  'Banff trip',
  FALSE,
  FALSE,
  '2026-04-18T12:00:00Z',
  '2026-04-18T12:00:00Z'
),
(
  'expense-3',
  'ws-1',
  'project-2',
  NULL,
  'production-2',
  'Color grading monitor',
  'Capital Asset',
  1599,
  '2026-04-17',
  'Increase post-production accuracy for deliverables and series work.',
  'Studio Workflow Refresh',
  TRUE,
  FALSE,
  '2026-04-17T16:10:00Z',
  '2026-04-17T16:10:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO people (
  id,
  workspace_id,
  full_name,
  person_type,
  role_summary,
  agreement_on_file,
  market_rate_justified,
  work_logs_linked,
  linked_project_ids,
  created_at,
  updated_at
) VALUES
(
  'person-1',
  'ws-1',
  'Maya Lin',
  'Editor',
  'Edited selects and delivery package for the series launch.',
  TRUE,
  TRUE,
  TRUE,
  ARRAY['project-1'],
  '2026-04-11T09:00:00Z',
  '2026-04-18T12:00:00Z'
),
(
  'person-2',
  'ws-1',
  'Alex Park',
  'Contractor',
  'Second camera operator for Banff field days.',
  FALSE,
  FALSE,
  FALSE,
  ARRAY['project-1'],
  '2026-04-11T09:15:00Z',
  '2026-04-18T12:00:00Z'
),
(
  'person-3',
  'ws-1',
  'Nina Lopez',
  'Assistant',
  'Studio reorganization and equipment documentation.',
  TRUE,
  TRUE,
  TRUE,
  ARRAY['project-2'],
  '2026-04-16T09:00:00Z',
  '2026-04-18T12:00:00Z'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO reminders (
  id,
  workspace_id,
  linked_type,
  linked_id,
  title,
  severity,
  due_date,
  note,
  created_at,
  updated_at
) VALUES
(
  'reminder-1',
  'ws-1',
  'Expense',
  'expense-2',
  'Upload Banff hotel receipt',
  'High',
  '2026-04-19',
  'Receipt threshold exceeded and business purpose is still blank.',
  '2026-04-18T09:00:00Z',
  '2026-04-18T09:00:00Z'
),
(
  'reminder-2',
  'ws-1',
  'Trip',
  'trip-1',
  'Finish trip closure questionnaire',
  'High',
  '2026-04-20',
  'Trip passed end date and is not ready for final close.',
  '2026-04-18T09:05:00Z',
  '2026-04-18T09:05:00Z'
),
(
  'reminder-3',
  'ws-1',
  'Person',
  'person-2',
  'Document contractor role and rate basis',
  'Medium',
  '2026-04-21',
  'Agreement, work log, and market-rate evidence are missing.',
  '2026-04-18T09:10:00Z',
  '2026-04-18T09:10:00Z'
)
ON CONFLICT (id) DO NOTHING;
